services:
  backend:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - .:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "start"]

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
